baseURL = 'https://bahboi.github.io/'
languageCode = "en-us"
title = "Attention"
theme="archie"
copyright = ""

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=3 # articles per page

[params]
	mode="toggle" # color-mode â†’ light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "I am testing my new blog"

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
# url = "https://github.com/athul/archie"

[[params.social]]
name = "Twitter"
icon = "twitter"
# rl = "https://twitter.com/athulcajay/"

[[params.social]]
name = "GitLab"
icon = "gitlab"
# url = "https://gitlab.com/athul/"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4